config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :closets do
    resources :skeletons
  end

  root to: "closets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/closet.rb
class Closet < ActiveRecord::Base
  has_many :skeletons
  validates(:name, presence: true)
end

app/models/skeleton.rb
class Skeleton < ActiveRecord::Base
  belongs_to :closet
  validates(:name, :body, presence: true)
  has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/closets_controller.rb
class ClosetsController < ApplicationController
  def index
    @closet = Closet.where.not(name: '')
  end

  def show
    @closet = Closet.find(params[:id])
    @visible_skeletons = @closet.skeletons.where(hide: false)
    @hidden_skeletons = @closet.skeletons.where(hide: true)
  end

  def new
    @closet = Closet.new
  end

  def create
    @closet = Closet.new(closet_params)
    if @closet.save!
      respond_to do |format|
        format.html { redirect_to closets_url }
        format.js
      end
    else
      render :new
    end
  end

  private
  def closet_params
    params.require(:closet).permit(:name)
  end
end

app/controllers/skeletons_controller.rb
class SkeletonsController < ApplicationController

  # def show
  #   @closet = Closet.find(params[:closet_id])
  #   @skeleton = Skeleton.find(params[:id])
  # end

  def new
    @closet = Closet.find(params[:closet_id])
    @skeleton = @closet.skeletons.new
  end

  def create
    @closet = Closet.find(params[:closet_id])
    @skeleton = @closet.skeletons.new(skeleton_params)
    if @skeleton.save!
      respond_to do |format|
        format.html { redirect_to closet_url(@skeleton.closet) }
        format.js
      end
    else
      render :new
    end
  end

  def edit
    @closet = Closet.find(params[:closet_id])
    @skeleton = Skeleton.find(params[:id])
  end

  def update
    @closet = Closet.find(params[:closet_id])
    @skeleton = Skeleton.find(params[:id])
    if @skeleton.update(skeleton_params)
      respond_to do |format|
        format.html { redirect_to closet_url(@skeleton.closet) }
        format.js
      end
    else
      render :edit
    end
  end

  def destroy
    @skeleton = Skeleton.find(params[:id])
    @skeleton.destroy
    redirect_to closet_path(@skeleton.closet)
  end

  private
  def skeleton_params
    params.require(:skeleton).permit(:name, :body, :hide, :picture)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/closets/_closet.html.erb
<h3><%= link_to closet.name, closet_path(closet) %></h3>

app/views/closets/_form.html.erb
<div id="closet-form">
  <%= render 'layouts/errors', :object => @closet %>
  <%= form_for @closet, remote: true do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, {class: "form-control"}  %>
  </div>
  <p><%= f.submit nil, {class: "btn btn-default"} %></p>
  <% end %>
</div>

app/views/closets/create.js.erb
$('#closet-form').remove();
$('#new_closet').show();
$('#closets').append('<%= j render(@closet) %>');

app/views/closets/index.html.erb
<h1>All the Closets</h1>

<div id="closets">
  <h3><%= render @closet %></h3>
</div>
<hr>
<h3><%= link_to "Add a Closet", new_closet_path, id:'new_closet', remote: true %></h3>

app/views/closets/new.html.erb
<h1>Add another closet</h1>

<%= render "form" %>

app/views/closets/new.js.erb
$('#new_closet').hide().after('<%= j render "form" %>');

app/views/closets/show.html.erb
<h4><%= link_to 'New Skeleton', new_closet_skeleton_path(@closet), id: 'new_skeleton', remote: true %></h4>

<div class="row">
  <div class="col-md-6">
    <div id="visible_skeletons">
      <h3>Skeletons of <em><%= @closet.name %></em></h3>
      <%= render @visible_skeletons %>
    </div>
  </div>
  <div class="col-md-6">
    <div class="closet">
      <h3>Hidden in Closet</h3>
        <%= render @hidden_skeletons %>
    </div>
  </div>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SkeletonCloset</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Arvo" rel="stylesheet">
  </head>

  <body>
    <div class="jumbotron">
      <div id="skull"><h1><%= link_to '💀', '/' %></h1></div>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/skeletons/_form.html.erb
<div id="skeleton-form">
  <%= render 'layouts/errors', :object => @skeleton %>
  <%= form_for [@closet, @skeleton], remote: true do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, {class: "form-control"}  %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, {class: "form-control"}  %>
  </div>
  <div class="form-group">
    <%= f.label :hide_in_closet %>
    <%= f.check_box :hide %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <p><%= f.submit nil, {class: "btn btn-default"} %></p>
  <% end %>
</div>

app/views/skeletons/_skeleton.html.erb
<h4><%= form_for skeleton, :url => closet_skeleton_path(skeleton.closet) do |f| %>
<%= f.check_box :hide %>
<%= f.submit "Hide Skeleton" %>
<%= f.label :hide, skeleton.name %>
<% end %></h4>

app/views/skeletons/_skeleton_details.html.erb
<%= image_tag(@skeleton.picture.url(:medium)) %>

<p>
  <%= @skeleton.body %>
</p>

<%= link_to "Edit Skeleton", edit_closet_skeleton_path(@closet, @skeleton) %> | <%= link_to "Delete Skeleton", closet_skeleton_path(@closet, @skeleton),
             :data => {:confirm => "Are you sure?",
            :method => "delete"} %>

app/views/skeletons/create.js.erb
$('#skeleton-form').remove();
$('#new_skeleton').show();
$('#visible_skeletons').append('<%= j render(@skeleton) %>');

app/views/skeletons/edit.html.erb
<h3>Have something to change?</h3>

<%= render "form" %>

app/views/skeletons/new.html.erb
<h3>Describe your skeleton...</h3>
<%= render "form" %>

app/views/skeletons/new.js.erb
$('#new_skeleton').hide().after('<%= j render "form" %>');